### ISSUE TITLE
Adding additional data (for instance, taxonomic id) about the different assemblies

### ISSUE THREAD

**Issue by jmfernandez** [fairtracks/fairtracks_standard#16]
I have just realized that we have barely modelled the assembly related to the tracks. Assemblies are from specific organisms, and there are many genomic data tracks from other organisms outside there.

So, I propose creating a new subschema to keep the list of recognized assemblies, with additional useful metadata attached to it.

Also, samples come from specific organisms, and it might be useful info to filter the tracks by organism. Yes, there are cases like tracks associated to samples from xenographs and tacks associated to samples from the mouse which grew the xenograph, which might be complicated to identify without that info.

**Comment by sveinugu** [comment]
@jmfernandez Yes, we should definitely have more assembly-related metadata.

The trackhub registry contains quite a bit of such metadata:

"species": {
      "type": "object",
      "title": "The organism/species of this collection of tracks.",
      "properties": {
        "tax_id": {
          "oneOf": [
            { "type": "integer", "minimum": 0, "exclusiveMinimum": true },
            { "type": "string", "pattern": "^[1-9][0-9]+?$" }
          ]
        },
        "scientific_name": { "type": "string" },
        "common_name": { "type": "string" }
      },
      "additionalProperties": false,
      "required": [ "tax_id", "scientific_name" ]
    },

    "assembly": {
      "type": "object",
      "title": "Assembly",
      "description": "Information which identifies the assembly referred to by this set of tracks.",
      "properties": {
        "accession": {
          "type": "string",
          "title": "NCBI Assembly accession ID",
          "description": "The NCBI assembly identifier (accession and version)",
          "pattern": "^G(CA|CF)_[0-9]+.[0-9]+$|^NA$"
        },
        "name": { "type": "string" },
        "long_name": { "type": "string" },
        "synonyms": { "type": "string" }
      },
      "additionalProperties": false,
      "required": [ "accession", "name" ]
    },

Here is an example (from their help page):

                 "species":{
                   "scientific_name":"Homo sapiens",
                   "common_name":"human",
                   "tax_id":"9606"
                 },
                 (...)
                 "assembly":{
                   "synonyms":"hg19",
                   "long_name":"Genome Reference Consortium Human Build 37 (GRCh37)",
                   "name":"GRCh37",
                   "accession":"GCA_000001405.1"
                 }

Most of this seems very useful. One should be able to autofill scientific and common_name from the tax id. As regards the assembly, I disagree a bit on the synonyms part. I mean, including synonyms in the model might be useful, but I don't think GRCh37 and hg19 are really synonyms. There are differences, as discussed in https://github.com/orgs/fairtracks/teams/fairtracks-developers/discussions/27. The long assembly name is perhaps the least useful, but I can see that can be used in a menu selection instead of "name"

Validation: You might need comletely new mechanisms for validating both species and assemblies, though? I suppose most of the species and assembly info is fetched from the ENSEMBL database and not annotated by the user. @dzerbino Is this database publicly available somehow for validation/auto-complete?

Each trackhub is connected to only one assembly, I think. But we can import directly from other repositories that can contain multiple assemblies, like IHEC. So we should support multiple species and assemblies within the schema. So in order not to duplicate info, we should actually create two new subschemas, as you propose..

I think having support for xenographs is pushing the standard a bit too far, though, but it could actually be handled by having an array as the genome_assembly attribute for the tracks.

**Comment by sveinugu** [comment]
For species validation, we should probably use the NCBI Taxonomy https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi

**Comment by sveinugu** [comment]
Ah, just realized that this is a UCSC-based standard, so the assembly database is probably the NCBI one: https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.26

**Comment by sveinugu** [comment]
Regarding synonyms. As 'hg38' etc. are not in the assemlby database as separate entities, we should probably instead add a flag or some other way to specify which of the chromosome notations the track follow (see https://github.com/orgs/fairtracks/teams/fairtracks-developers/discussions/27)

**Comment by sveinugu** [comment]
Aaaaaand thinking a bit more, I see that I have complicated this too much. As there are databases available, we do not need to duplicate the content here, but instead provide urls, as we are also doing for other similar info, e.g. biosample. So I think all of this can be reduced to two pairs of attributes:

- species_name (scientific)
- species_url
- assembly_name
- assembly_url

We could then use assembly_name to specify whether we follow e.g. GRCh38 or hg38 chromosome namings, as discussed before

**Comment by sveinugu** [comment]
Validating species_name and assembly_name would require specific extensions, somehow, though. But we can probably postpone that a bit.

**Comment by sveinugu** [comment]
Waaait. identifiers.org to the rescue??

**Comment by nerdstrike** [comment]
Given that the species information here is largely populated by the Trackhub Registry, you probably don't need to validate it unless there is something you don't like about what we're doing at the moment.

Users only provide a UCSC or Ensembl species name, or a valid GCA to register a hub. We insert the rest of the information from our various sources.

**Comment by jmfernandez** [comment]
> Waaait. identifiers.org to the rescue??

At least for species, yes:

https://registry.identifiers.org/registry/taxonomy

which covers 99.99% the cases. But, we should think on a fallback when organism is or cannot fully be catalogued.

**Comment by sveinugu** [comment]
For genome assemblies: https://registry.identifiers.org/registry/insdc.gca#!

**Comment by sveinugu** [comment]
Ok, so I think I finally have the UCSC (hg) - NCBI/GRCh chromosome naming issue figured out (after 12 years!):

- UCSC reference genomes have traditionally been equal in sequence to the initial release of the human reference genome (initially NCBI until NCBI18/hg18, changed into GRCh from GRCh37/hg19, and moved to the same number from GRCh38/hg38).
- The chromosome naming in UCSC is different, though: chr1 instead of 1, and so on. Most track files use the UCSC convention, in my experience. 
- The human reference genome consists of the chromosomes, the mithocondrial chromosome, and a set of alternative sequences, typically for immune-related regions.  I think they are all haplotypes (e.g. set of variants commonly inherited together), but not fully sure of the terminology here. I don't think it matters for us anyway.
- Reference genome patches have traditionally not been imported to UCSC, as they are not coordinate-changing. The patches are either updates to the reference sequences (FIX) or adds novel alternative sequences (NOVEL): https://www.ncbi.nlm.nih.gov/grc/help/patches/
-  The reference mitochondrial genome was added from GRCh37.p2 onwards, but hg19 is points to the initial release (GRC37) which did not include the mitochondrial genome. UCSC then added a non-reference mitochondrial genome which is not present in the NCBI reference genomes.
- International Nucleotide Sequence Database Collaboration (INSDC) is a collaboration between  DDBJ, EMBL-EBI and NCBI, which all have reference assembly databases. For EMBL-EBI the reference assemblies are in ENA (e.g. https://www.ebi.ac.uk/ena/data/view/GCA_000001405.28).
- Both NCBI and EBI databases are available through namespaces in identifiers.org ("insdc.gca" and "ena"). The "incds.gca" namespace is exclusively for genome assemblyes and is named "Genome assembly database". Both of them resolve into both databases (https://identifiers.org/resolve?query=insdc.gca:GCA_000001405.1 and http://identifiers.org/resolve?query=ena.embl:GCA000001405.1). Identifiers.org has bugs in both cases though. insdc.gca does not support versions number > 9, while ena does not support the required underscore for the GCA accession numbers. I will add issues (or pull requests) for both of these.
- The NCBI database correctly names the initial release of each human reference genome with the UCSC synonym (e.g. https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.13/ has 'hg19' as synonym, but https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.14/ does not). ENA does not provide the synonym tag.
- The GCF_ accession numbers are the Refseq ones for the official reference sequences, while GCA_ accession numbers are for those references that recide in GenBank. I think all (or at least most) GCF sequences have a GCA counterpart, but they might differ slightly, which they do in the most recent versions of the human reference sequence, e.g. https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.38/. The difference is here one alternative sequence in GCA that is not included in GCF.
- There are other unofficial reference genomes primarily used to improve variant calling, e.g. including the decoy sequences from the 1000 Genomes Project. Nice overview here: http://lh3.github.io/2017/11/13/which-human-reference-genome-to-use. As far as I understand, the resulting tracks are still meant to map to the official reference genome, it is only a mapping technicality.
- @dzerbino I don't know how this issue has been handled in the Track Hub Registry, though. Perhaps you can enlighten? It is in any case not so important for our solution as we are generating a new standard.

So what to conclude from this?

1. We will use the "incds.gca" namespace and not "ena", as the first is exclusive to genome assemblies. One could have added a JSON Schema pattern filter for "ena" to make sure that the accession numbers are GCA/GCF, but that seems an unnecessary complication.
2. We will primarily make use of the NCBI database, due to the "synonym" attribute. It also has a better interface, IMO..
3. We will include both "assembly_id" and "assembly_name", with the first being a "insdc.gca" CURIE
4. If the track file follows UCSC-style coordinates, assembly_name should be hgXX instead of NCBIXX/GCRhXX.
5. We can use the NCBI database to validate assembly_name to be either the official name of the synonym
6. I will provide some issues/pull requests to the identifiers.org github

**Comment by sveinugu** [comment]
The only issue I can see with the above is that in the case of hg19 tracks, they might contain chrM coordinates that are not precent in GCA_000001405.1 (which hg19 is a synonym for). However this is an issue for the tools to handle, primarily by making use of the UCSC genome assembly files instead of the official ones. The metadata is still as sound as we can make them, as the UCSC hg19 reference genome is the non-standard one.

We could think about providing (or linking to) a reference genome mapping service that handles both the UCSC case and also mapping between genome reference versions (e.g., https://www.ncbi.nlm.nih.gov/genome/tools/remap or https://genome.ucsc.edu/cgi-bin/hgLiftOver). But that is for the future.

**Comment by sveinugu** [comment]
Regarding the patches: 

I suggest the following two rules

1. Tracks should be annotated with the lowest required version of the reference genome

 Thus:
  - Tracks without references to specific alternative sequences available only in patched versions should be annotated with the initial genome reference assembly, e.g. GRHh38.
  - For tracks with references to alternative sequences should be annotated with the minimal version needed to resolve the chromosome names
  - Tracks that are based upon a specific patch of the reference genome, e.g. gene predictions, should still be generally annotated with the lowest reference genome version required to identify the sequence references. This in order to more easily combine e.g. recent gene predictions with older tracks.
  - We could think of adding info on the genome assembly version used to generate the track, but that should then also include support for non-standard references (e.g. including decoys). This is definitely for the future.

The above rule (minimal genome assembly version) is anyway a recommendation that is hard to enforce.

2. Use GCF ids (refseq) if they are present
- Only exception (AFAIK) is the rare cases where the track refers to a sequence in GCA that is not included in GCF)

**Comment by sveinugu** [comment]
BTW, UCSC is now finally adding patches, but in a new unstandard way: 
  - http://genome.ucsc.edu/blog/patches/
  - For any tracks that refer to the UCSC novel alternative sequences (or patches) just have to be denoted "hgXX" and with the GCF id of the initial reference genome, as with the hg19 chrM sequence. The tools will have to handle this. An second field for recording the genome assembly version used to generate the track could be used to improve the situation in this case also.

**Comment by sveinugu** [comment]
Perhaps a better alternative to add a second genome assembly version field is to add an array of sequence ids of the sequences used. However, I think this is way too detailed info for FAIRtracks.

**Comment by sveinugu** [comment]
Fixed by https://github.com/fairtracks/fairtracks_standard/pull/33
